name: friends_lms
description: A beautifully crafted LMS Flutter app with stunning onboarding, role selection, and login screens.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.2.6
  table_calendar: ^3.0.9
  file_picker: ^8.1.2
  fl_chart: ^0.63.0
  http: ^1.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  animate_do: ^3.3.4
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/questions.json
